from django.urls import path
from .views import *
urlpatterns = [
    path('user_login/',UserLoginView.as_view(),name='user_login'),
    path('',UserDashboardView.as_view(),name='user_dashboard'),
    path('user_profile/',UserProfileView.as_view(),name='user_profile'),
    path('UserEditProfile/',UserEditProfileView.as_view(),name='UserEditProfile'),
    path('shipping_address/',ShippingAddressCreateView.as_view(),name='shipping_address'),
    path('user_change_password/',UserChangePasswordView.as_view(),name='user_change_password'),
    path('UserEditAddress/',UserShippingEditView.as_view(),name='UserEditAddress'),
    path('UserShippingEditAddress/',ShippingAddressEditView.as_view(),name='UserShippingEditAddress'),
    path('cart/',CartAddView.as_view(),name='cart'),
    path('cart/remove/<int:item_id>/',CartRemoveView.as_view(),name='cart_remove'),
    path('cart/update/', CartUpdateView.as_view(), name='cart_update'),
    path('cartview/',CartView.as_view(),name='cartview'),
    path('user_registration/',UserRegistrationView.as_view(),name='user_registration'),
    path('seller_registration/',SellerRegistrationView.as_view(),name='seller_registration'),
    path('shop/',ShopView.as_view(),name='shop'),
    path('book/<int:pk>/',BookDetailView.as_view(),name='BookDetail'),
    path('author/<int:author_id>/books/',AuthorBooksView.as_view(),name='author_books'),
    path('wishlist/add/',WishlistView.as_view(),name='add_to_wishlist'),
    path('wishlist/',WishlistShowView.as_view(),name='wishlist_view'),
    path('wishlist/remove/<int:pk>/', WishlistRemoveView.as_view(), name='remove_from_wishlist'),
    path('apply-coupon/', ApplyCouponView.as_view(), name='apply_coupon'),
    path('cart/remove-coupon/', RemoveCouponView.as_view(), name='remove_coupon'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('delete-shipping-address/<int:pk>/', DeleteShippingAddressView.as_view(), name='delete_shipping_address'),
    path("save-shipping-address/", SaveShippingAddressView.as_view(), name="save_shipping_address"),
    path('track-order/', TrackOrderView.as_view(), name='track_order'),
    path('my-orders/', PastOrdersView.as_view(), name='past_orders'),
    path('about/', AboutView.as_view(), name='about'),
    path('services/', ServicesView.as_view(), name='services'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('rate/order/<int:order_id>/', OrderRatingView.as_view(), name='rate_order_books'),
    path('submit/ratings/<int:order_id>/', SubmitOrderRatingsView.as_view(), name='submit_order_ratings'),
    path('ratings/user/<int:user_id>/', RatingListView.as_view(), name='user_rating_list'),
    path('review/submit/', BookstoreReviewView.as_view(), name='submit-website-review'),
    path("user_logout/",LogoutView.as_view(),name="user_logout"),

]
