# Generated by Django 5.2 on 2025-05-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='photo',
            new_name='image',
        ),
    ]
