# Generated by Django 5.2 on 2025-05-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0002_rename_photo_author_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='image',
            new_name='author_image',
        ),
    ]
