# Generated by Django 5.2 on 2025-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0004_publication_book_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='publications/'),
        ),
    ]
