# Generated by Django 5.2 on 2025-05-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0009_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
