# Generated by Django 5.2 on 2025-06-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0010_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cod', 'COD')], default='code', max_length=50),
        ),
    ]
