# Generated by Django 5.2 on 2025-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0014_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Australia', 'Australia'), ('Canada', 'Canada')], max_length=100, null=True),
        ),
    ]
