# Generated by Django 5.2 on 2025-06-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0018_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='shipping_addresses',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone_number',
            new_name='shipping_phone_number',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='pincodes',
            new_name='shipping_pincodes',
        ),
    ]
