# Generated by Django 5.2 on 2025-06-18 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0019_rename_address_shippingaddress_shipping_addresses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstall.shippingaddress'),
        ),
    ]
