# Generated by Django 5.2 on 2025-06-25 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0020_bookorder_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
